/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:17058ee3-9ef5-4856-92e2-0157f628afbb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6ZC0658Ze",
    "aws_user_pools_web_client_id": "5g7o1eviq099lge2vdfqotljd4",
    "oauth": {}
};


export default awsmobile;
